name: Lint JSON

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '00 05 */7 * *'
  workflow_dispatch: 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Lint
      run: python make_new_sites.py
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Lint updates'
        add: sites.json
        default_author: github_actions
        push: true
